cmake_minimum_required(VERSION 4.0)
project(CPlusPlus)

set(CMAKE_CXX_STANDARD 20)

add_executable(CPlusPlus main.cpp
        no0003_Longest_Substring_Without_Repeating_Characters.cpp
        no1768_Merge_Strings_Alternately.cpp
        no0027_Remove_Element.cpp
        no0206_Reverse_Linked_List.cpp
        no0146_LRU_Cache.cpp
        no0056_Merge_Intervals.cpp
        no1188_Design_Bounded_Blocking_Queue.cpp
        no1116_Print_Zero_Even_Odd.cpp
        Breadh_First_Search.cpp
        no0226_Invert_Binary_Tree.cpp
        no0373_Find_K_Pairs_with_Smallest_Sums.cpp
        no0442_Find_All_Duplicates_in_an_Array.cpp
        no0005_Longest_Palindromic_Substring.cpp
        no0035_Search_Insert_Position.cpp
        Binary_Search.cpp
        Quick_Sort.cpp
        Depth_First_Search.cpp
        no0058_Length_of_Last_Word.cpp)
