cmake_minimum_required(VERSION 4.0)
project(CPlusPlus)

set(CMAKE_CXX_STANDARD 20)

add_executable(CPlusPlus main.cpp
        no0003_Longest_Substring_Without_Repeating_Characters.cpp
        no1768_Merge_Strings_Alternately.cpp
        no0027_Remove_Element.cpp
        no0206_Reverse_Linked_List.cpp
        no0146_LRU_Cache.cpp
        no0056_Merge_Intervals.cpp
        no1188_Design_Bounded_Blocking_Queue.cpp
        no1116_Print_Zero_Even_Odd.cpp
        Breadh_First_Search.cpp)
